version: "3.9"

services:
  notebot:
    image: notebot
    build: .
    container_name: notebot
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./repo:/repo